import pkg from '@reduxjs/toolkit';
const {configureStore, createSlice} = pkg;
import {v4 as uuidv4} from 'uuid';

const initialState = {
	commands: [],
	newCommand: '',
	activeCommand: null,
	inputMode: false,
};

const parseCommand = raw => {
	const [root, ...args] = raw.includes(' ') ? raw.split(' ') : [raw];
	return {
		id: uuidv4(),
		raw,
		root,
		args,
	};
};

const rootSlice = createSlice({
	name: 'root',
	initialState,
	reducers: {
		setInitial: (_, {payload}) => {
			const commands = payload.map(parseCommand);
			return {
				activeCommand: commands[0]?.id,
				commands,
			};
		},
		addCommand: ({commands, ...state}, {payload}) => ({
			...state,
			inputMode: false,
			newCommand: '',
			commands: [...commands, parseCommand(payload)],
		}),
		deleteCommand: ({commands, activeCommand, ...state}) => ({
			...state,
			activeCommand: commands[0]?.id,
			commands: commands.filter(command => command.id !== activeCommand),
		}),
		setInputMode: (state, {payload}) => ({
			...state,
			newCommand: '',
			inputMode: payload,
		}),
		inputCharacter: ({newCommand, ...state}, {payload}) => ({
			...state,
			newCommand: newCommand + payload,
		}),
		inputDelete: ({newCommand, ...state}) => ({
			...state,
			inputMode: newCommand.length > 1,
			newCommand: newCommand.slice(0, -1),
		}),
		setActive: (state, {payload}) => ({...state, activeCommand: payload}),
	},
	// The `extraReducers` field lets the slice handle actions defined elsewhere,
	// including actions generated by createAsyncThunk or in other slices.
	// extraReducers: builder => {
	// 	builder
	// 		.addCase(incrementAsync.pending, state => {
	// 			state.status = 'loading';
	// 		})
	// 		.addCase(incrementAsync.fulfilled, (state, action) => {
	// 			state.status = 'idle';
	// 			state.value += action.payload;
	// 		});
	// },
});

export const {
	setInitial,
	addCommand,
	deleteCommand,
	inputCharacter,
	inputDelete,
	setInputMode,
	setActive,
} = rootSlice.actions;

export const store = configureStore({
	reducer: {
		root: rootSlice.reducer,
	},
});
